name: Run Unit Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pytest pandas scikit-learn
          python -c "import sys, os; print(sys.path)"  # Debug path
      - name: Run tests
        run: |
          PYTHONPATH=$PYTHONPATH:${{ github.workspace }} pytest tests/ -v
